[[redirects]]
  from = "/api/*"
  to = "http://3.27.120.54/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "http://3.27.120.54/:splat"
  status = 200
  force = true


