[[redirects]]
  from = "/api/*"
  to = "http://www.taskperfect.somee.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "http://www.taskperfect.somee.com/:splat"
  status = 200
  force = true


  [[redirects]]
from="/*"
to="index.html"
status=200


